interop: add missing include for libc++
interop/PassStore.cpp:52:23: error: implicit instantiation of undefined template 'std::basic_stringstream<char>'
                stringstream path = stringstream(getenv("PATH"));
                                    ^
/usr/include/c++/v1/iosfwd:142:32: note: template is declared here
    class _LIBCPP_TEMPLATE_VIS basic_stringstream;
                               ^
interop/PassStore.cpp:52:16: error: implicit instantiation of undefined template 'std::basic_stringstream<char>'
                stringstream path = stringstream(getenv("PATH"));
                             ^
/usr/include/c++/v1/iosfwd:142:32: note: template is declared here
    class _LIBCPP_TEMPLATE_VIS basic_stringstream;
                               ^